library(dplyr)
library(tidyr)
## The downloaded file is first unpacked in Windows
## Due to some regional settings, the weekday names in my plots do not appear in English
rr8 <- read.table("./household_power_consumption.txt", header = T, sep = ";", stringsAsFactors = FALSE)
rr8$Date <- as.Date(rr8$Date, "%d/%m/%Y")
rr8in <- subset(rr8, rr8$Date == "2007-02-01" | rr8$Date == "2007-02-02")
rr8in$Sub_metering_1 <- as.numeric(rr8in$Sub_metering_1)
rr8in$Sub_metering_2 <- as.numeric(rr8in$Sub_metering_2)
rr8in$Sub_metering_3 <- as.numeric(rr8in$Sub_metering_3)
rr8in$Global_active_power <- as.numeric(rr8in$Global_active_power)
rr8in$Global_reactive_power <- as.numeric(rr8in$Global_reactive_power)
rr8in$Voltage <- as.numeric(rr8in$Voltage)
rr8un <- unite(rr8in, DaTi, Date, Time, sep = " ", remove = FALSE)
rr8un$DaTi <- strptime(rr8un$DaTi, format = "%Y-%m-%d %H:%M:%S")
png(filename = "plot4.png", width = 480, height = 480)
par(mfcol = c(2,2), mar = c(4, 4, 2, 1))
with(rr8un, plot(DaTi, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power"))
with(rr8un, plot(DaTi, Sub_metering_1, main = "", xlab = "", ylab = "Energy sub metering", type = "n"))
with(rr8un, lines(DaTi, Sub_metering_1))
with(rr8un, lines(DaTi, Sub_metering_2, col = "red"))
with(rr8un, lines(DaTi, Sub_metering_3, col = "blue"))
legend("topright", col = c("black", "red", "blue"), pch = 3, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with(rr8un, plot(DaTi, Voltage, type = "l", xlab = "datetime", ylab = "Voltage"))
with(rr8un, plot(DaTi, Global_reactive_power, type = "l", xlab = "datetime"))
dev.off()