library(dplyr)
library(tidyr)
## The downloaded file is first unpacked in Windows
## Due to some regional settings, the weekday names in my plots do not appear in English
rr7 <- read.table("./household_power_consumption.txt", header = T, sep = ";", stringsAsFactors = FALSE)
rr7$Date <- as.Date(rr7$Date, "%d/%m/%Y")
rr7in <- subset(rr7, rr7$Date == "2007-02-01" | rr7$Date == "2007-02-02")
rr7in$Sub_metering_1 <- as.numeric(rr7in$Sub_metering_1)
rr7in$Sub_metering_2 <- as.numeric(rr7in$Sub_metering_2)
rr7in$Sub_metering_3 <- as.numeric(rr7in$Sub_metering_3)
rr7un <- unite(rr7in, DaTi, Date, Time, sep = " ", remove = FALSE)
rr7un$DaTi <- strptime(rr7un$DaTi, format = "%Y-%m-%d %H:%M:%S")
png(filename = "plot3.png", width = 480, height = 480)
with(rr7un, plot(DaTi, Sub_metering_1, main = "", xlab = "", ylab = "Energy sub metering", type = "n"))
with(rr7un, lines(DaTi, Sub_metering_1))
with(rr7un, lines(DaTi, Sub_metering_2, col = "red"))
with(rr7un, lines(DaTi, Sub_metering_3, col = "blue"))
legend("topright", col = c("black", "red", "blue"), pch = 3, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()